[package]
name = "hyperscanemu"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[[bin]]
name = "hyperscan-emu"
path = "src/main.rs"

[dependencies]
hyperscanemu-core = { path = "../hyperscanemu-core" }
hyperscanemu-media = { path = "../hyperscanemu-media" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
cpal = "0.18.1"
image = { version = "0.25", default-features = false, features = ["png"] }
minifb = "0.28"
